collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

domain: qingchen177.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://qingchen177.github.io  # the base hostname and protocol for your site, e.g. http://example.com    # place folder name if the site is served in a subfolder
baseurl: /jekyll-demo